name: "Manual"
on:
  workflow_dispatch:

  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/manual.yml'


jobs:
  build:
    runs-on: macos-12
    env:
      RELEASE: 8.0
      DEBUG: 1
    steps:
    - uses: actions/checkout@v2
    - name: Sleep
      run: |
        for i in $(seq 1 10) ; do echo $i; sleep 1; done
        echo "please loging to ssh below, and run 'bash build.sh conf/netbsd-$RELEASE.conf'"
    - uses: neilpang/debugger-action@master

#    - run: |
#        bash build.sh conf/netbsd-$RELEASE.conf





